services:
  - type: web
    name: telegram-voice-bot
    runtime: python
    region: oregon
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn bot:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: RENDER_EXTERNAL_URL
        fromService:
          type: web
          name: telegram-voice-bot
          property: url
    autoDeploy: true

